### ISSUE TITLE
feedback of what I want as a feature:

### ISSUE THREAD

**Issue by PROBSLOZER** [AwMan3703/art-cheatsheet-maker#2]
**Is your feature request related to a problem? Please describe.**
You’re gay

**Describe the solution you'd like**
You gay

**Describe alternatives you've considered**
Subway Surfers gameplay on the side pls and you can also mute it pls

**Additional context**
I’m you’re boyfriend so you have to do it 
![Uploading IMG_3666.jpeg…]()

**Comment by AwMan3703** [comment]
Feature was added in v1.5, 1.5dev and 1.5-it, update pushed 17:40 2024/09/12 :)
I love u bb<3
