### ISSUE TITLE
Very bas

### ISSUE THREAD

**Issue by PROBSLOZER** [AwMan3703/art-cheatsheet-maker#3]
**Describe the bug**
No subway surfers that you can also mute gameplay on the side 

**To Reproduce**
1. Add it 
2. Add it
3. Add it
4. Add it

**Expected behavior**
I want it 

**Screenshots**
My peanuts 

**Desktop (please complete the following information):**
 Me ipad 

**Smartphone (please complete the following information):**
 Me phone

**Additional context**
I’m you’re boufriejd

**Comment by AwMan3703** [comment]
Added in v1.5, 1.5dev and 1.5-it
